name: CI

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "**/package.json"

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm --filter frontend run build

      - name: Build backend
        run: pnpm --filter backend run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: "**/package.json"

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm --filter frontend run lint

      - name: Run Prettier check
        run: pnpm --filter frontend run format:check
